### PR TITLE
SEN-2566 Add recipe for isNotEqualTo instead of !equals isTrue

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by bbogason** [comment]
It's hard to review PRs that have commits that are not relevant. Consider removing those commits and leaving only the commit(s) that pertain to "adding recipe for isNotEqualTo instead of !equals isTrue"

**Review by bbogason — APPROVED** [review]
I only reviewed this commit: f82d060a88438dce1c92f9291de812c34eb6fafe

Looks good to me. If there was anything in the other 6 commits I was supposed to review then please consider my review to be unfinished.

**Comment by seanf** [comment]
> It's hard to review PRs that have commits that are not relevant. Consider removing those commits and leaving only the commit(s) that pertain to "adding recipe for isNotEqualTo instead of !equals isTrue"

Sorry about that, but I really wanted to avoid merge conflicts with my other assertj test code. There really _was_ only one extra commit, and hopefully the Jira tags were clear enough in the commit titles. 

It's a real shame GitHub isn't better at managing PRs on top of other PRs. I guess I should have targetted the earlier PR branch though.

**Comment by seanf** [comment]
> I only reviewed this commit: f82d060

Rewritten to 51288188b9

**Pull request merged**
